swagger: '2.0'
info:
  description: This is the description of the Standard API
  version: 1.1.0
  title: GDSO standard API
  termsOfService: https://gdso.org/getattachment/Members-description/Technical-documentation/Section/Terms-of-Use/GDSO-GeneralTermsofUse_Production_FEB2023-(1).pdf?lang=en-US
  contact:
    email: info@gdso.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
tags:
  - name: tire
    description: Everything about your Tire
    externalDocs:
      description: Find out more
      url: https://gdso-org.github.io/tech-doc/
schemes:
  - http
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
paths:
  /tire/{sgtin}:
    get:
      tags:
        - tire
      summary: get tire information from a sgtin96 tag
      security:
        - OAuth2:
            - read
      description: Returns product information related to this individual tire. This operation requires authentication.
      operationId: getTireBySgtin
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: sgtin
          description: serial number of the tire to get information on. It must be an existing SGTIN96 serial number in pureId form (urn:epc:id:sgtin:086699.0337140.9413672970)
          required: true
          type: string
        - in: query
          name: country
          description: API request's country of origin (ISO 2-digits code)
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Tire'
        '400':
          description: bad request
        '404':
          description: Tire not found / Invalid sgtin supplied
definitions:
  Labelling:
    description: Labelling
    type: array
    items:
      type: object
      properties:
        noisePerformance:
          type: integer
          description: Labelling noise performance
          example: 70
        noiseClass:
          type: string
          description: Labelling noise class
          example: C4
        rollingResistanceClass:
          type: string
          description: Labelling Rolling Resistance class
          example: B
        wetClass:
          type: string
          description: Labelling wet class
          example: C
        labellingReferenceRegulation:
          type: string
          description: Regulation to which the labelling level of the tire for wet, noise and rolling resistance is given.
          example: EUR DIR 1222/2009
        eprelRecordReferenceUrl:
          type: string
          description: URL to the EPREL record of the tire
          example: https://www.eprel.com/reference/123456
        labelPictureUrl:
          type: string
          description: URL to the label picture
          example: https://www.michelin.com/label/product/123456
  ItemIDS:
    description: various Item/article IDs
    properties:
      eanCode:
        type: string
        description: European Article number according to GS1 standard
        example: '3528709789509'
      upcCode:
        type: string
        description: (Private) Universal Product code according to GS1 standard
        example: '00412345678'
  Dimensions:
    description: dimensions of the tire
    properties:
      geometricalTyreSize:
        type: string
        description: Tyre size designation
        example: 195/65 R 17
      sectionWidth:
        type: object
        description: Nominal section width of the tire
        properties:
          value:
            type: number
            description: section width value
            example: 195
          uom:
            type: string
            description: unit of measure for section width
            enum:
              - MILLIMETER
              - INCH
            example: MILLIMETER
      aspectRatio:
        type: integer
        description: Aspect Ratio
        example: 65
      rimCode:
        type: object
        properties:
          value:
            type: number
            description: Rim diameter
            example: 17
          uom:
            type: string
            description: unit of measure for the rim diameter
            enum:
              - MILLIMETER
              - INCH
            example: INCH
  Specifications:
    description: specifications of the tire (load index, speed symbol ...)
    properties:
      loadIndex:
        type: integer
        description: Load index
        example: 87
      loadIndexForDualFitment:
        type: integer
        description: Load index for dual fitment
        example: 88
      speedSymbol:
        type: string
        description: Speed symbol
        example: H
      speedSymbolSupplementaryServiceCondition:
        type: string
        description: For commercial tires, load adjusted speed
        example: I
      loadIndexSupplementaryServiceCondition:
        type: integer
        description: For commercial tires, speed adjusted load
        example: 85
      loadIndexSupplementaryServiceConditionDualFitment:
        type: integer
        description: For commercial tires, speed adjusted load for dual fitment
        example: 86
      structure:
        type: string
        description: Structure Radial or Bias
        enum:
          - R
          - B
        example: R
      tubeCharacteristic:
        type: string
        description: It indicates tubeless or tube type tyres
        enum:
          - TT
          - TL
        example: TL
      extraLoadOrReinforced:
        type: boolean
        description: Extra Load symbol to be associated to the load index if needed
        example: true
      directional:
        type: boolean
        description: Directional arrow marking - it indicates the rotation sens of the tire
        example: true
      asymetrical:
        type: boolean
        description: It indicates if the tire as a specific mounting sens (OUTSIDE marking)
        example: false
      runFlat:
        type: string
        description: It indicates the capability of the tire to run without pressure
        example: E
      sealant:
        type: boolean
        description: It indicates the fact that the tire is equipped with a puncture sealant
        example: true
      maxLoadCarryingCapacity:
        type: integer
        description: (Private) Load capacity (kg) per axle at max inflation pressure (kPa) and at the specified speed
        example: 1200
      hlpc:
        type: boolean
        description: Indicates if the tire meets the UN R.30 definition of High Load (HL), values according to ETRTO standard
        example: true
  Markings:
    description: different markings of the tire (M+S, POR ...)
    properties:
      mudAndSnow:
        type: boolean
        description: Mud and Snow (M+S) marking
        example: true
      3pmsf:
        type: boolean
        description: 3PMSF marking to indicate if the tire is designed for use in severe snow conditions
        example: true
      iceGrip:
        type: boolean
        description: Ice grip marking to indicate the tire performance on ice
        example: true
      tractionTire:
        type: boolean
        description: Traction regulatory marking (UNECE R117) Tires primarly designed for the drive axle to maximise torque transmission in various circumstances
        example: true
      freeRollingTire:
        type: boolean
        description: FRT marking Tire designed for equipment of trailer axles, axles of motor vehicles other than front steering and drive axles.
        example: true
      professionnalOfRoad:
        type: boolean
        description: POR marking Tire designed for service in severe off road conditions
        example: true
      sizeSuffix:
        type: string
        description: Part of identification marking of the tire (see G9 ETRTO Std Manual T = temporary, P = Passenger for TRA std, LT = light truck (alternative to C Marking of R54)
        enum:
          - C
          - CP
        example: CP
      sizePrefix:
        type: string
        description: Part of identification marking of tire (see G9 ETRTO Std Manual T = temporary, P ou LT)
        enum:
          - T
          - P
          - LT
        example: T
      OEMarking:
        type: array
        items:
          type: object
          properties:
            oemName:
              type: string
              description: Specific original equipment marking - OEM Name
              example: Mercedes
            tireMarking:
              type: string
              description: Specific original equipment marking
              example: MO
      maxInflationPressure:
        type: integer
        description: (Private) Max tyre inflation pressure in kPa
        example: 530
  NationalRegulationsCompliances:
    description: (Private) Compliance information to national regulations
    type: array
    items:
      type: object
      properties:
        marking:
          type: string
          description: Regulation name or marking
          example: CCC
  Weight:
    description: (Private) weight of the tire
    properties:
      value:
        type: number
        description: tire weight value
        example: 10.5
      uom:
        type: string
        description: unit of measure for tire weight
        enum:
          - KILOGRAM
        example: KILOGRAM
  VectoCoefficient:
    description: (Private) DECLARED COEFFICIENT VALUE (N/kN) according to EU 2017/2400 Regulation
    properties:
      value:
        type: number
        description: coefficient value
        example: 7.0
      uom:
        type: string
        description: unit of measure for coefficient
        enum:
          - N/kN
        example: N/kN
  WltpCoefficient:
    description: (Private) Aligned COEFFICIENT VALUE (N/kN) according to EU 2017/1151 Regulation
    properties:
      value:
        type: number
        description: WLTP Tyre Rolling coefficient value
        example: 5.6
      uom:
        type: string
        description: unit of measure for WLTP coefficient
        enum:
          - kg/T
        example: kg/T
  TyreRollingCircumference:
    description: (Private) Theoretical Tyre Rolling Circumference - Calculated according to ETRTO for PC and CV tyres (TRA for LT) and reported in mm
    properties:
      value:
        type: number
        description: Circumference value
        example: 1720
      uom:
        type: string
        description: unit of measure for circumference value
        enum:
          - MILLIMETER
        example: MILLIMETER
  Tire:
    properties:
      uii:
        type: string
        description: (Private) Unique Item Identifier - SGTIN-96 following Pure identity EPC URN (GS1 EPCIS) format
        example : "urn:epc:id:sgtin:12345678.04444.2222222"
      product:
        $ref: '#/definitions/Product'
      dotTin:
        type: object
        description: (Private) Tire Identification Number (consisting of Plant Code, Size Code and Type Code) (US Market )
        properties:
          factoryCode:
            type: string
            description: Production zone/plant of the tire
            example: B3
          sizeCode:
            type: string
            description: tire size code
            example: 8U
          optionalCode:
            type: string
            description: tire optional code
            example: 005X
          weekYear:
            type: string
            description: tire production week
            example: '1020'
      countryOfOrigin:
        type: string
        description: (Private) ISO code on 3 characters that indicates the tire's country of origin
        example: ITA
      nationalRegulationsComplianceCode:
        type: number
        description: (Private) Code that indicates compliance of tire to specific international legal market requirement based on PRICAT standard
        example: 105
      nationalRegulationsCompliances:
        $ref: '#/definitions/NationalRegulationsCompliances'
      weight:
        $ref: '#/definitions/Weight'
      vectoTyreRollingResistance:
        $ref: '#/definitions/VectoCoefficient'
      vectoCertificateNumber:
        type: string
        description: (Private) Certificate number according to EU 2017/2400 Regulation format in ASCII
        example: e4*2017/2400*2022/1379*T*01002*00
      rollingCircumference:
        $ref: '#/definitions/TyreRollingCircumference'
      wltpTyreRollingResistance:
        $ref: '#/definitions/WltpCoefficient'
      developmentIdentifier:
        type: string
        description: (Private) Specification/Identification used during tyre developement. Alpha numeric code used by the Stakeholders if applicable in ASCII
        example: A1234568A
      customerPartNumber:
        type: string
        description: (Private) Internal reference for customer Prototype / Series. Alpha numeric code used by the OEM if applicable in ASCII
        example: X1Y2-Z
      oemSubmissionIdentifier:
        type: string
        description: (Private) Id provided by the OEM for specific technical requirements submittal during the vehicle / tyre development cycles, so that variants for the same specification can be distinguished by them.
        example: A1B2C3...
    xml:
      name: Tire
  Product:
    properties:
      itemIDS:
        $ref: '#/definitions/ItemIDS'
      commercialNameLongDescription:
        type: string
        description: Marketing text / Commercial name of the product
        example: 195/65 R 17 87H TL Dakota Spring
      brandName:
        type: string
        description: Manufacturer’s name or brand name
        example: Bravetyre
      commercialName:
        type: string
        description: Commercial Name
        example: Dakota Spring
      dimensions:
        $ref: '#/definitions/Dimensions'
      specifications:
        $ref: '#/definitions/Specifications'
      markings:
        $ref: '#/definitions/Markings'
      productType:
        type: string
        description: Marketing appreciation of the targeted product usage based on manufacturer classification based on PRICAT standard
        example: 110
      labelling:
        $ref: '#/definitions/Labelling'
      nonGradingEligibility:
        type: boolean
        description: Non grading elegibility according to ??
        example: false
      labelTireClassAssociated:
        type: string
        description: C1 / C2 / C3 tyre
        example: C1
      supplierId:
        type: string
        description: (Private) Supplier Number or Vendor Number assigned to a tyre manufacturer by the OEM to identify the company (alphanumeric field)
        example: A1B2C3D4
      urls:
        type: array
        items:
          type: object
          properties:
            website:
              type: string
              description: type of the web site the URL is pointing on
              enum:
                - Brand
                - Product
              example: Brand
            url:
              type: string
              description: URL of the website
              example: http://www.gdso.org
  ApiResponse:
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    xml:
      name: '##default'